/*
 * AUTO-GENERATED by scripts/generate-data.js — do not edit by hand.
 * Ion — Phase 2 demo inventory (real layouts/areas from "ion brochure Final",
 * prices computed per-m² from the published price list).
 */
(function (root) {
  "use strict";
  var DATA = {
  "project": {
    "name": "Ion",
    "phase": "Phase 2",
    "developer": "Prime Developments",
    "tagline": "Innovative living",
    "deliveryText": "4 Years"
  },
  "buildings": [
    {
      "code": "B01",
      "pin": {
        "x": 0.75,
        "y": 0.79
      },
      "units": [
        {
          "code": "B01-202",
          "building": "B01",
          "floor": "2nd",
          "bedrooms": 3,
          "type": "3 Bedrooms",
          "category": "Typical Apartment",
          "finish": "Fully Finished",
          "area": 149,
          "view": "Landscape",
          "price": 7433312,
          "floorplan": "3br-t3"
        },
        {
          "code": "B01-204",
          "building": "B01",
          "floor": "2nd",
          "bedrooms": 3,
          "type": "3 Bedrooms",
          "category": "Typical Apartment",
          "finish": "Fully Finished",
          "area": 149,
          "view": "Pool",
          "price": 7433312,
          "floorplan": "3br-t3"
        },
        {
          "code": "B01-205",
          "building": "B01",
          "floor": "2nd",
          "bedrooms": 4,
          "type": "4 Bedrooms",
          "category": "Typical Apartment",
          "finish": "Fully Finished",
          "area": 200,
          "view": "Landscape",
          "price": 10043000,
          "floorplan": "4br-t3"
        },
        {
          "code": "B01-401",
          "building": "B01",
          "floor": "4th",
          "bedrooms": 3,
          "type": "3 Bedrooms",
          "category": "Typical Apartment",
          "finish": "Fully Finished",
          "area": 149,
          "view": "Pool",
          "price": 7433312,
          "floorplan": "3br-t3"
        },
        {
          "code": "B01-402",
          "building": "B01",
          "floor": "4th",
          "bedrooms": 4,
          "type": "4 Bedrooms",
          "category": "Typical Apartment",
          "finish": "Fully Finished",
          "area": 226,
          "view": "Garden",
          "price": 11348590,
          "floorplan": "4br-t1"
        },
        {
          "code": "B01-501",
          "building": "B01",
          "floor": "5th",
          "bedrooms": 3,
          "type": "3 Bedrooms",
          "category": "Typical Apartment",
          "finish": "Fully Finished",
          "area": 159,
          "view": "Street",
          "price": 7932192,
          "floorplan": "3br-t7"
        },
        {
          "code": "B01-702",
          "building": "B01",
          "floor": "7th",
          "bedrooms": 2,
          "type": "2 Bedrooms",
          "category": "Typical Apartment",
          "finish": "Fully Finished",
          "area": 124,
          "view": "Garden",
          "price": 6422580,
          "floorplan": "2br-t1"
        },
        {
          "code": "B01-706",
          "building": "B01",
          "floor": "7th",
          "bedrooms": 4,
          "type": "4 Bedrooms",
          "category": "Typical Apartment",
          "finish": "Fully Finished",
          "area": 197,
          "view": "Landscape",
          "price": 9892355,
          "floorplan": "4br-t4"
        }
      ]
    },
    {
      "code": "B02",
      "pin": {
        "x": 0.627,
        "y": 0.771
      },
      "units": [
        {
          "code": "B02-106",
          "building": "B02",
          "floor": "1st",
          "bedrooms": 4,
          "type": "4 Bedrooms",
          "category": "Typical Apartment",
          "finish": "Fully Finished",
          "area": 200,
          "view": "Landscape",
          "price": 10043000,
          "floorplan": "4br-t3"
        },
        {
          "code": "B02-203",
          "building": "B02",
          "floor": "2nd",
          "bedrooms": 4,
          "type": "4 Bedrooms",
          "category": "Typical Apartment",
          "finish": "Fully Finished",
          "area": 200,
          "view": "Street",
          "price": 10043000,
          "floorplan": "4br-t3"
        },
        {
          "code": "B02-303",
          "building": "B02",
          "floor": "3rd",
          "bedrooms": 3,
          "type": "3 Bedrooms",
          "category": "Typical Apartment",
          "finish": "Fully Finished",
          "area": 149,
          "view": "Landscape",
          "price": 7433312,
          "floorplan": "3br-t3"
        },
        {
          "code": "B02-404",
          "building": "B02",
          "floor": "4th",
          "bedrooms": 3,
          "type": "3 Bedrooms",
          "category": "Typical Apartment",
          "finish": "Fully Finished",
          "area": 149,
          "view": "Pool",
          "price": 7433312,
          "floorplan": "3br-t3"
        },
        {
          "code": "B02-504",
          "building": "B02",
          "floor": "5th",
          "bedrooms": 4,
          "type": "4 Bedrooms",
          "category": "Typical Apartment",
          "finish": "Fully Finished",
          "area": 197,
          "view": "Garden",
          "price": 9892355,
          "floorplan": "4br-t4"
        },
        {
          "code": "B02-506",
          "building": "B02",
          "floor": "5th",
          "bedrooms": 4,
          "type": "4 Bedrooms",
          "category": "Typical Apartment",
          "finish": "Fully Finished",
          "area": 222,
          "view": "Garden",
          "price": 11147730,
          "floorplan": "4br-t2"
        },
        {
          "code": "B02-602",
          "building": "B02",
          "floor": "6th",
          "bedrooms": 4,
          "type": "4 Bedrooms",
          "category": "Typical Apartment",
          "finish": "Fully Finished",
          "area": 226,
          "view": "Garden",
          "price": 11348590,
          "floorplan": "4br-t1"
        },
        {
          "code": "B02-605",
          "building": "B02",
          "floor": "6th",
          "bedrooms": 3,
          "type": "3 Bedrooms",
          "category": "Typical Apartment",
          "finish": "Fully Finished",
          "area": 183,
          "view": "Landscape",
          "price": 9129504,
          "floorplan": "3br-t6"
        },
        {
          "code": "B02-705",
          "building": "B02",
          "floor": "7th",
          "bedrooms": 3,
          "type": "3 Bedrooms",
          "category": "Typical Apartment",
          "finish": "Fully Finished",
          "area": 197,
          "view": "Landscape",
          "price": 9827936,
          "floorplan": "3br-t5"
        }
      ]
    },
    {
      "code": "B03",
      "pin": {
        "x": 0.377,
        "y": 0.797
      },
      "units": [
        {
          "code": "B03-201",
          "building": "B03",
          "floor": "2nd",
          "bedrooms": 2,
          "type": "2 Bedrooms",
          "category": "Typical Apartment",
          "finish": "Fully Finished",
          "area": 123,
          "view": "Street",
          "price": 6370785,
          "floorplan": "2br-t3"
        },
        {
          "code": "B03-304",
          "building": "B03",
          "floor": "3rd",
          "bedrooms": 3,
          "type": "3 Bedrooms",
          "category": "Typical Apartment",
          "finish": "Fully Finished",
          "area": 169,
          "view": "Landscape",
          "price": 8431072,
          "floorplan": "3br-t4"
        },
        {
          "code": "B03-306",
          "building": "B03",
          "floor": "3rd",
          "bedrooms": 2,
          "type": "2 Bedrooms",
          "category": "Typical Apartment",
          "finish": "Fully Finished",
          "area": 140,
          "view": "Garden",
          "price": 7251300,
          "floorplan": "2br-t2"
        },
        {
          "code": "B03-406",
          "building": "B03",
          "floor": "4th",
          "bedrooms": 3,
          "type": "3 Bedrooms",
          "category": "Typical Apartment",
          "finish": "Fully Finished",
          "area": 197,
          "view": "Street",
          "price": 9827936,
          "floorplan": "3br-t5"
        },
        {
          "code": "B03-506",
          "building": "B03",
          "floor": "5th",
          "bedrooms": 3,
          "type": "3 Bedrooms",
          "category": "Typical Apartment",
          "finish": "Fully Finished",
          "area": 169,
          "view": "Pool",
          "price": 8431072,
          "floorplan": "3br-t4"
        },
        {
          "code": "B03-601",
          "building": "B03",
          "floor": "6th",
          "bedrooms": 4,
          "type": "4 Bedrooms",
          "category": "Typical Apartment",
          "finish": "Fully Finished",
          "area": 222,
          "view": "Landscape",
          "price": 11147730,
          "floorplan": "4br-t2"
        },
        {
          "code": "B03-606",
          "building": "B03",
          "floor": "6th",
          "bedrooms": 4,
          "type": "4 Bedrooms",
          "category": "Typical Apartment",
          "finish": "Fully Finished",
          "area": 222,
          "view": "Street",
          "price": 11147730,
          "floorplan": "4br-t2"
        },
        {
          "code": "B03-704",
          "building": "B03",
          "floor": "7th",
          "bedrooms": 4,
          "type": "4 Bedrooms",
          "category": "Typical Apartment",
          "finish": "Fully Finished",
          "area": 197,
          "view": "Garden",
          "price": 9892355,
          "floorplan": "4br-t4"
        },
        {
          "code": "B03-706",
          "building": "B03",
          "floor": "7th",
          "bedrooms": 2,
          "type": "2 Bedrooms",
          "category": "Typical Apartment",
          "finish": "Fully Finished",
          "area": 123,
          "view": "Street",
          "price": 6370785,
          "floorplan": "2br-t3"
        }
      ]
    },
    {
      "code": "B04",
      "pin": {
        "x": 0.254,
        "y": 0.824
      },
      "units": [
        {
          "code": "B04-204",
          "building": "B04",
          "floor": "2nd",
          "bedrooms": 3,
          "type": "3 Bedrooms",
          "category": "Typical Apartment",
          "finish": "Fully Finished",
          "area": 149,
          "view": "Landscape",
          "price": 7433312,
          "floorplan": "3br-t3"
        },
        {
          "code": "B04-306",
          "building": "B04",
          "floor": "3rd",
          "bedrooms": 3,
          "type": "3 Bedrooms",
          "category": "Typical Apartment",
          "finish": "Fully Finished",
          "area": 159,
          "view": "Landscape",
          "price": 7932192,
          "floorplan": "3br-t7"
        },
        {
          "code": "B04-403",
          "building": "B04",
          "floor": "4th",
          "bedrooms": 4,
          "type": "4 Bedrooms",
          "category": "Typical Apartment",
          "finish": "Fully Finished",
          "area": 200,
          "view": "Street",
          "price": 10043000,
          "floorplan": "4br-t3"
        },
        {
          "code": "B04-502",
          "building": "B04",
          "floor": "5th",
          "bedrooms": 4,
          "type": "4 Bedrooms",
          "category": "Typical Apartment",
          "finish": "Fully Finished",
          "area": 222,
          "view": "Street",
          "price": 11147730,
          "floorplan": "4br-t2"
        },
        {
          "code": "B04-503",
          "building": "B04",
          "floor": "5th",
          "bedrooms": 3,
          "type": "3 Bedrooms",
          "category": "Typical Apartment",
          "finish": "Fully Finished",
          "area": 149,
          "view": "Landscape",
          "price": 7433312,
          "floorplan": "3br-t3"
        },
        {
          "code": "B04-605",
          "building": "B04",
          "floor": "6th",
          "bedrooms": 3,
          "type": "3 Bedrooms",
          "category": "Typical Apartment",
          "finish": "Fully Finished",
          "area": 204,
          "view": "Landscape",
          "price": 10177152,
          "floorplan": "3br-t2"
        }
      ]
    },
    {
      "code": "B05",
      "pin": {
        "x": 0.239,
        "y": 0.648
      },
      "units": [
        {
          "code": "B05-103",
          "building": "B05",
          "floor": "1st",
          "bedrooms": 2,
          "type": "2 Bedrooms",
          "category": "Typical Apartment",
          "finish": "Fully Finished",
          "area": 123,
          "view": "Garden",
          "price": 6370785,
          "floorplan": "2br-t3"
        },
        {
          "code": "B05-105",
          "building": "B05",
          "floor": "1st",
          "bedrooms": 2,
          "type": "2 Bedrooms",
          "category": "Typical Apartment",
          "finish": "Fully Finished",
          "area": 140,
          "view": "Pool",
          "price": 7251300,
          "floorplan": "2br-t2"
        },
        {
          "code": "B05-206",
          "building": "B05",
          "floor": "2nd",
          "bedrooms": 4,
          "type": "4 Bedrooms",
          "category": "Typical Apartment",
          "finish": "Fully Finished",
          "area": 226,
          "view": "Landscape",
          "price": 11348590,
          "floorplan": "4br-t1"
        },
        {
          "code": "B05-303",
          "building": "B05",
          "floor": "3rd",
          "bedrooms": 3,
          "type": "3 Bedrooms",
          "category": "Typical Apartment",
          "finish": "Fully Finished",
          "area": 197,
          "view": "Garden",
          "price": 9827936,
          "floorplan": "3br-t5"
        },
        {
          "code": "B05-305",
          "building": "B05",
          "floor": "3rd",
          "bedrooms": 3,
          "type": "3 Bedrooms",
          "category": "Typical Apartment",
          "finish": "Fully Finished",
          "area": 159,
          "view": "Garden",
          "price": 7932192,
          "floorplan": "3br-t7"
        },
        {
          "code": "B05-306",
          "building": "B05",
          "floor": "3rd",
          "bedrooms": 4,
          "type": "4 Bedrooms",
          "category": "Typical Apartment",
          "finish": "Fully Finished",
          "area": 226,
          "view": "Landscape",
          "price": 11348590,
          "floorplan": "4br-t1"
        }
      ]
    },
    {
      "code": "B06",
      "pin": {
        "x": 0.217,
        "y": 0.455
      },
      "units": [
        {
          "code": "B06-203",
          "building": "B06",
          "floor": "2nd",
          "bedrooms": 3,
          "type": "3 Bedrooms",
          "category": "Typical Apartment",
          "finish": "Fully Finished",
          "area": 183,
          "view": "Pool",
          "price": 9129504,
          "floorplan": "3br-t6"
        },
        {
          "code": "B06-301",
          "building": "B06",
          "floor": "3rd",
          "bedrooms": 3,
          "type": "3 Bedrooms",
          "category": "Typical Apartment",
          "finish": "Fully Finished",
          "area": 204,
          "view": "Landscape",
          "price": 10177152,
          "floorplan": "3br-t2"
        },
        {
          "code": "B06-302",
          "building": "B06",
          "floor": "3rd",
          "bedrooms": 3,
          "type": "3 Bedrooms",
          "category": "Typical Apartment",
          "finish": "Fully Finished",
          "area": 169,
          "view": "Street",
          "price": 8431072,
          "floorplan": "3br-t4"
        },
        {
          "code": "B06-402",
          "building": "B06",
          "floor": "4th",
          "bedrooms": 2,
          "type": "2 Bedrooms",
          "category": "Typical Apartment",
          "finish": "Fully Finished",
          "area": 124,
          "view": "Garden",
          "price": 6422580,
          "floorplan": "2br-t1"
        },
        {
          "code": "B06-603",
          "building": "B06",
          "floor": "6th",
          "bedrooms": 3,
          "type": "3 Bedrooms",
          "category": "Typical Apartment",
          "finish": "Fully Finished",
          "area": 159,
          "view": "Street",
          "price": 7932192,
          "floorplan": "3br-t7"
        },
        {
          "code": "B06-701",
          "building": "B06",
          "floor": "7th",
          "bedrooms": 3,
          "type": "3 Bedrooms",
          "category": "Typical Apartment",
          "finish": "Fully Finished",
          "area": 149,
          "view": "Pool",
          "price": 7433312,
          "floorplan": "3br-t3"
        }
      ]
    },
    {
      "code": "B07",
      "pin": {
        "x": 0.239,
        "y": 0.333
      },
      "units": [
        {
          "code": "B07-102",
          "building": "B07",
          "floor": "1st",
          "bedrooms": 3,
          "type": "3 Bedrooms",
          "category": "Typical Apartment",
          "finish": "Fully Finished",
          "area": 183,
          "view": "Street",
          "price": 9129504,
          "floorplan": "3br-t6"
        },
        {
          "code": "B07-106",
          "building": "B07",
          "floor": "1st",
          "bedrooms": 2,
          "type": "2 Bedrooms",
          "category": "Typical Apartment",
          "finish": "Fully Finished",
          "area": 123,
          "view": "Pool",
          "price": 6370785,
          "floorplan": "2br-t3"
        },
        {
          "code": "B07-202",
          "building": "B07",
          "floor": "2nd",
          "bedrooms": 3,
          "type": "3 Bedrooms",
          "category": "Typical Apartment",
          "finish": "Fully Finished",
          "area": 169,
          "view": "Landscape",
          "price": 8431072,
          "floorplan": "3br-t4"
        },
        {
          "code": "B07-204",
          "building": "B07",
          "floor": "2nd",
          "bedrooms": 3,
          "type": "3 Bedrooms",
          "category": "Typical Apartment",
          "finish": "Fully Finished",
          "area": 190,
          "view": "Street",
          "price": 9478720,
          "floorplan": "3br-t1"
        },
        {
          "code": "B07-206",
          "building": "B07",
          "floor": "2nd",
          "bedrooms": 4,
          "type": "4 Bedrooms",
          "category": "Typical Apartment",
          "finish": "Fully Finished",
          "area": 222,
          "view": "Landscape",
          "price": 11147730,
          "floorplan": "4br-t2"
        },
        {
          "code": "B07-304",
          "building": "B07",
          "floor": "3rd",
          "bedrooms": 3,
          "type": "3 Bedrooms",
          "category": "Typical Apartment",
          "finish": "Fully Finished",
          "area": 183,
          "view": "Pool",
          "price": 9129504,
          "floorplan": "3br-t6"
        },
        {
          "code": "B07-402",
          "building": "B07",
          "floor": "4th",
          "bedrooms": 4,
          "type": "4 Bedrooms",
          "category": "Typical Apartment",
          "finish": "Fully Finished",
          "area": 225,
          "view": "Garden",
          "price": 11298375,
          "floorplan": "4br-t5"
        },
        {
          "code": "B07-406",
          "building": "B07",
          "floor": "4th",
          "bedrooms": 3,
          "type": "3 Bedrooms",
          "category": "Typical Apartment",
          "finish": "Fully Finished",
          "area": 190,
          "view": "Garden",
          "price": 9478720,
          "floorplan": "3br-t1"
        },
        {
          "code": "B07-705",
          "building": "B07",
          "floor": "7th",
          "bedrooms": 3,
          "type": "3 Bedrooms",
          "category": "Typical Apartment",
          "finish": "Fully Finished",
          "area": 183,
          "view": "Garden",
          "price": 9129504,
          "floorplan": "3br-t6"
        }
      ]
    },
    {
      "code": "B08",
      "pin": {
        "x": 0.25,
        "y": 0.137
      },
      "units": [
        {
          "code": "B08-101",
          "building": "B08",
          "floor": "1st",
          "bedrooms": 3,
          "type": "3 Bedrooms",
          "category": "Typical Apartment",
          "finish": "Fully Finished",
          "area": 149,
          "view": "Garden",
          "price": 7433312,
          "floorplan": "3br-t3"
        },
        {
          "code": "B08-104",
          "building": "B08",
          "floor": "1st",
          "bedrooms": 4,
          "type": "4 Bedrooms",
          "category": "Typical Apartment",
          "finish": "Fully Finished",
          "area": 225,
          "view": "Landscape",
          "price": 11298375,
          "floorplan": "4br-t5"
        },
        {
          "code": "B08-204",
          "building": "B08",
          "floor": "2nd",
          "bedrooms": 4,
          "type": "4 Bedrooms",
          "category": "Typical Apartment",
          "finish": "Fully Finished",
          "area": 225,
          "view": "Street",
          "price": 11298375,
          "floorplan": "4br-t5"
        },
        {
          "code": "B08-403",
          "building": "B08",
          "floor": "4th",
          "bedrooms": 4,
          "type": "4 Bedrooms",
          "category": "Typical Apartment",
          "finish": "Fully Finished",
          "area": 197,
          "view": "Street",
          "price": 9892355,
          "floorplan": "4br-t4"
        },
        {
          "code": "B08-406",
          "building": "B08",
          "floor": "4th",
          "bedrooms": 3,
          "type": "3 Bedrooms",
          "category": "Typical Apartment",
          "finish": "Fully Finished",
          "area": 169,
          "view": "Street",
          "price": 8431072,
          "floorplan": "3br-t4"
        },
        {
          "code": "B08-602",
          "building": "B08",
          "floor": "6th",
          "bedrooms": 3,
          "type": "3 Bedrooms",
          "category": "Typical Apartment",
          "finish": "Fully Finished",
          "area": 190,
          "view": "Landscape",
          "price": 9478720,
          "floorplan": "3br-t1"
        },
        {
          "code": "B08-704",
          "building": "B08",
          "floor": "7th",
          "bedrooms": 3,
          "type": "3 Bedrooms",
          "category": "Typical Apartment",
          "finish": "Fully Finished",
          "area": 169,
          "view": "Street",
          "price": 8431072,
          "floorplan": "3br-t4"
        }
      ]
    },
    {
      "code": "B09",
      "pin": {
        "x": 0.402,
        "y": 0.257
      },
      "units": [
        {
          "code": "B09-202",
          "building": "B09",
          "floor": "2nd",
          "bedrooms": 4,
          "type": "4 Bedrooms",
          "category": "Typical Apartment",
          "finish": "Fully Finished",
          "area": 222,
          "view": "Street",
          "price": 11147730,
          "floorplan": "4br-t2"
        },
        {
          "code": "B09-301",
          "building": "B09",
          "floor": "3rd",
          "bedrooms": 3,
          "type": "3 Bedrooms",
          "category": "Typical Apartment",
          "finish": "Fully Finished",
          "area": 204,
          "view": "Garden",
          "price": 10177152,
          "floorplan": "3br-t2"
        },
        {
          "code": "B09-304",
          "building": "B09",
          "floor": "3rd",
          "bedrooms": 4,
          "type": "4 Bedrooms",
          "category": "Typical Apartment",
          "finish": "Fully Finished",
          "area": 200,
          "view": "Pool",
          "price": 10043000,
          "floorplan": "4br-t3"
        },
        {
          "code": "B09-305",
          "building": "B09",
          "floor": "3rd",
          "bedrooms": 3,
          "type": "3 Bedrooms",
          "category": "Typical Apartment",
          "finish": "Fully Finished",
          "area": 204,
          "view": "Landscape",
          "price": 10177152,
          "floorplan": "3br-t2"
        },
        {
          "code": "B09-505",
          "building": "B09",
          "floor": "5th",
          "bedrooms": 3,
          "type": "3 Bedrooms",
          "category": "Typical Apartment",
          "finish": "Fully Finished",
          "area": 190,
          "view": "Garden",
          "price": 9478720,
          "floorplan": "3br-t1"
        },
        {
          "code": "B09-506",
          "building": "B09",
          "floor": "5th",
          "bedrooms": 3,
          "type": "3 Bedrooms",
          "category": "Typical Apartment",
          "finish": "Fully Finished",
          "area": 204,
          "view": "Garden",
          "price": 10177152,
          "floorplan": "3br-t2"
        },
        {
          "code": "B09-605",
          "building": "B09",
          "floor": "6th",
          "bedrooms": 4,
          "type": "4 Bedrooms",
          "category": "Typical Apartment",
          "finish": "Fully Finished",
          "area": 226,
          "view": "Landscape",
          "price": 11348590,
          "floorplan": "4br-t1"
        },
        {
          "code": "B09-702",
          "building": "B09",
          "floor": "7th",
          "bedrooms": 4,
          "type": "4 Bedrooms",
          "category": "Typical Apartment",
          "finish": "Fully Finished",
          "area": 225,
          "view": "Pool",
          "price": 11298375,
          "floorplan": "4br-t5"
        },
        {
          "code": "B09-705",
          "building": "B09",
          "floor": "7th",
          "bedrooms": 4,
          "type": "4 Bedrooms",
          "category": "Typical Apartment",
          "finish": "Fully Finished",
          "area": 200,
          "view": "Garden",
          "price": 10043000,
          "floorplan": "4br-t3"
        }
      ]
    },
    {
      "code": "B10",
      "pin": {
        "x": 0.533,
        "y": 0.32
      },
      "units": [
        {
          "code": "B10-102",
          "building": "B10",
          "floor": "1st",
          "bedrooms": 4,
          "type": "4 Bedrooms",
          "category": "Typical Apartment",
          "finish": "Fully Finished",
          "area": 200,
          "view": "Garden",
          "price": 10043000,
          "floorplan": "4br-t3"
        },
        {
          "code": "B10-103",
          "building": "B10",
          "floor": "1st",
          "bedrooms": 4,
          "type": "4 Bedrooms",
          "category": "Typical Apartment",
          "finish": "Fully Finished",
          "area": 197,
          "view": "Street",
          "price": 9892355,
          "floorplan": "4br-t4"
        },
        {
          "code": "B10-201",
          "building": "B10",
          "floor": "2nd",
          "bedrooms": 4,
          "type": "4 Bedrooms",
          "category": "Typical Apartment",
          "finish": "Fully Finished",
          "area": 222,
          "view": "Pool",
          "price": 11147730,
          "floorplan": "4br-t2"
        },
        {
          "code": "B10-306",
          "building": "B10",
          "floor": "3rd",
          "bedrooms": 3,
          "type": "3 Bedrooms",
          "category": "Typical Apartment",
          "finish": "Fully Finished",
          "area": 169,
          "view": "Garden",
          "price": 8431072,
          "floorplan": "3br-t4"
        },
        {
          "code": "B10-501",
          "building": "B10",
          "floor": "5th",
          "bedrooms": 3,
          "type": "3 Bedrooms",
          "category": "Typical Apartment",
          "finish": "Fully Finished",
          "area": 169,
          "view": "Garden",
          "price": 8431072,
          "floorplan": "3br-t4"
        },
        {
          "code": "B10-503",
          "building": "B10",
          "floor": "5th",
          "bedrooms": 3,
          "type": "3 Bedrooms",
          "category": "Typical Apartment",
          "finish": "Fully Finished",
          "area": 169,
          "view": "Street",
          "price": 8431072,
          "floorplan": "3br-t4"
        },
        {
          "code": "B10-504",
          "building": "B10",
          "floor": "5th",
          "bedrooms": 3,
          "type": "3 Bedrooms",
          "category": "Typical Apartment",
          "finish": "Fully Finished",
          "area": 159,
          "view": "Landscape",
          "price": 7932192,
          "floorplan": "3br-t7"
        }
      ]
    },
    {
      "code": "B11",
      "pin": {
        "x": 0.634,
        "y": 0.432
      },
      "units": [
        {
          "code": "B11-204",
          "building": "B11",
          "floor": "2nd",
          "bedrooms": 3,
          "type": "3 Bedrooms",
          "category": "Typical Apartment",
          "finish": "Fully Finished",
          "area": 197,
          "view": "Garden",
          "price": 9827936,
          "floorplan": "3br-t5"
        },
        {
          "code": "B11-401",
          "building": "B11",
          "floor": "4th",
          "bedrooms": 3,
          "type": "3 Bedrooms",
          "category": "Typical Apartment",
          "finish": "Fully Finished",
          "area": 169,
          "view": "Garden",
          "price": 8431072,
          "floorplan": "3br-t4"
        },
        {
          "code": "B11-403",
          "building": "B11",
          "floor": "4th",
          "bedrooms": 4,
          "type": "4 Bedrooms",
          "category": "Typical Apartment",
          "finish": "Fully Finished",
          "area": 197,
          "view": "Pool",
          "price": 9892355,
          "floorplan": "4br-t4"
        },
        {
          "code": "B11-405",
          "building": "B11",
          "floor": "4th",
          "bedrooms": 3,
          "type": "3 Bedrooms",
          "category": "Typical Apartment",
          "finish": "Fully Finished",
          "area": 183,
          "view": "Garden",
          "price": 9129504,
          "floorplan": "3br-t6"
        },
        {
          "code": "B11-501",
          "building": "B11",
          "floor": "5th",
          "bedrooms": 3,
          "type": "3 Bedrooms",
          "category": "Typical Apartment",
          "finish": "Fully Finished",
          "area": 204,
          "view": "Garden",
          "price": 10177152,
          "floorplan": "3br-t2"
        },
        {
          "code": "B11-604",
          "building": "B11",
          "floor": "6th",
          "bedrooms": 4,
          "type": "4 Bedrooms",
          "category": "Typical Apartment",
          "finish": "Fully Finished",
          "area": 197,
          "view": "Street",
          "price": 9892355,
          "floorplan": "4br-t4"
        },
        {
          "code": "B11-702",
          "building": "B11",
          "floor": "7th",
          "bedrooms": 3,
          "type": "3 Bedrooms",
          "category": "Typical Apartment",
          "finish": "Fully Finished",
          "area": 149,
          "view": "Garden",
          "price": 7433312,
          "floorplan": "3br-t3"
        },
        {
          "code": "B11-704",
          "building": "B11",
          "floor": "7th",
          "bedrooms": 3,
          "type": "3 Bedrooms",
          "category": "Typical Apartment",
          "finish": "Fully Finished",
          "area": 149,
          "view": "Pool",
          "price": 7433312,
          "floorplan": "3br-t3"
        }
      ]
    },
    {
      "code": "B12",
      "pin": {
        "x": 0.728,
        "y": 0.602
      },
      "units": [
        {
          "code": "B12-202",
          "building": "B12",
          "floor": "2nd",
          "bedrooms": 3,
          "type": "3 Bedrooms",
          "category": "Typical Apartment",
          "finish": "Fully Finished",
          "area": 204,
          "view": "Garden",
          "price": 10177152,
          "floorplan": "3br-t2"
        },
        {
          "code": "B12-203",
          "building": "B12",
          "floor": "2nd",
          "bedrooms": 3,
          "type": "3 Bedrooms",
          "category": "Typical Apartment",
          "finish": "Fully Finished",
          "area": 149,
          "view": "Pool",
          "price": 7433312,
          "floorplan": "3br-t3"
        },
        {
          "code": "B12-301",
          "building": "B12",
          "floor": "3rd",
          "bedrooms": 4,
          "type": "4 Bedrooms",
          "category": "Typical Apartment",
          "finish": "Fully Finished",
          "area": 222,
          "view": "Garden",
          "price": 11147730,
          "floorplan": "4br-t2"
        },
        {
          "code": "B12-302",
          "building": "B12",
          "floor": "3rd",
          "bedrooms": 2,
          "type": "2 Bedrooms",
          "category": "Typical Apartment",
          "finish": "Fully Finished",
          "area": 140,
          "view": "Pool",
          "price": 7251300,
          "floorplan": "2br-t2"
        },
        {
          "code": "B12-403",
          "building": "B12",
          "floor": "4th",
          "bedrooms": 3,
          "type": "3 Bedrooms",
          "category": "Typical Apartment",
          "finish": "Fully Finished",
          "area": 159,
          "view": "Pool",
          "price": 7932192,
          "floorplan": "3br-t7"
        },
        {
          "code": "B12-602",
          "building": "B12",
          "floor": "6th",
          "bedrooms": 3,
          "type": "3 Bedrooms",
          "category": "Typical Apartment",
          "finish": "Fully Finished",
          "area": 183,
          "view": "Landscape",
          "price": 9129504,
          "floorplan": "3br-t6"
        }
      ]
    }
  ],
  "assets": {
    "masterplan": "assets/masterplan-web.jpg",
    "renders": [
      "assets/pdf/render1.jpg",
      "assets/pdf/render2.jpg",
      "assets/pdf/render3.jpg"
    ]
  },
  "isSeed": true
};
  if (typeof module !== "undefined" && module.exports) module.exports = DATA;
  else root.OfferData = DATA;
})(typeof window !== "undefined" ? window : this);
