/*
 * AUTO-GENERATED by scripts/generate-data.js — do not edit by hand.
 * Ion — Phase 2 demo inventory (real prices/areas, demo unit codes/floors/views).
 */
(function (root) {
  "use strict";
  var DATA = {
  "project": {
    "name": "Ion",
    "phase": "Phase 2",
    "developer": "Prime Developments",
    "tagline": "Innovative living",
    "deliveryText": "4 Years"
  },
  "buildings": [
    {
      "code": "B01",
      "pin": {
        "x": 0.227,
        "y": 0.135
      },
      "units": [
        {
          "code": "B01-202",
          "building": "B01",
          "floor": "2nd",
          "bedrooms": 2,
          "type": "2 Bedrooms",
          "category": "Typical Apartment",
          "finish": "Fully Finished",
          "area": 129,
          "view": "Landscape",
          "price": 6681555,
          "floorplan": "2br-b"
        },
        {
          "code": "B01-204",
          "building": "B01",
          "floor": "2nd",
          "bedrooms": 2,
          "type": "2 Bedrooms",
          "category": "Typical Apartment",
          "finish": "Fully Finished",
          "area": 129,
          "view": "Pool",
          "price": 6681555,
          "floorplan": "2br-b"
        },
        {
          "code": "B01-205",
          "building": "B01",
          "floor": "2nd",
          "bedrooms": 3,
          "type": "3 Bedrooms",
          "category": "Typical Apartment",
          "finish": "Fully Finished",
          "area": 183,
          "view": "Landscape",
          "price": 9017760,
          "floorplan": "3br-d"
        },
        {
          "code": "B01-401",
          "building": "B01",
          "floor": "4th",
          "bedrooms": 2,
          "type": "2 Bedrooms",
          "category": "Typical Apartment",
          "finish": "Fully Finished",
          "area": 129,
          "view": "Pool",
          "price": 6681555,
          "floorplan": "2br-b"
        },
        {
          "code": "B01-402",
          "building": "B01",
          "floor": "4th",
          "bedrooms": 3,
          "type": "3 Bedrooms",
          "category": "Typical Apartment",
          "finish": "Fully Finished",
          "area": 177,
          "view": "Garden",
          "price": 8888055,
          "floorplan": "3br-c"
        },
        {
          "code": "B01-501",
          "building": "B01",
          "floor": "5th",
          "bedrooms": 3,
          "type": "3 Bedrooms",
          "category": "Typical Apartment",
          "finish": "Fully Finished",
          "area": 173,
          "view": "Street",
          "price": 8687195,
          "floorplan": "3br-b"
        },
        {
          "code": "B01-702",
          "building": "B01",
          "floor": "7th",
          "bedrooms": 2,
          "type": "2 Bedrooms",
          "category": "Typical Apartment",
          "finish": "Fully Finished",
          "area": 113,
          "view": "Garden",
          "price": 5852835,
          "floorplan": "2br-a"
        },
        {
          "code": "B01-706",
          "building": "B01",
          "floor": "7th",
          "bedrooms": 4,
          "type": "4 Bedrooms",
          "category": "Typical Apartment",
          "finish": "Fully Finished",
          "area": 179,
          "view": "Landscape",
          "price": 8988485,
          "floorplan": "4br-a"
        }
      ]
    },
    {
      "code": "B02",
      "pin": {
        "x": 0.388,
        "y": 0.139
      },
      "units": [
        {
          "code": "B02-106",
          "building": "B02",
          "floor": "1st",
          "bedrooms": 3,
          "type": "3 Bedrooms",
          "category": "Typical Apartment",
          "finish": "Fully Finished",
          "area": 183,
          "view": "Landscape",
          "price": 9017760,
          "floorplan": "3br-d"
        },
        {
          "code": "B02-203",
          "building": "B02",
          "floor": "2nd",
          "bedrooms": 3,
          "type": "3 Bedrooms",
          "category": "Typical Apartment",
          "finish": "Fully Finished",
          "area": 190,
          "view": "Street",
          "price": 9478811,
          "floorplan": "3br-d"
        },
        {
          "code": "B02-303",
          "building": "B02",
          "floor": "3rd",
          "bedrooms": 2,
          "type": "2 Bedrooms",
          "category": "Typical Apartment",
          "finish": "Fully Finished",
          "area": 129,
          "view": "Landscape",
          "price": 6681555,
          "floorplan": "2br-b"
        },
        {
          "code": "B02-404",
          "building": "B02",
          "floor": "4th",
          "bedrooms": 2,
          "type": "2 Bedrooms",
          "category": "Typical Apartment",
          "finish": "Fully Finished",
          "area": 129,
          "view": "Pool",
          "price": 6681555,
          "floorplan": "2br-b"
        },
        {
          "code": "B02-504",
          "building": "B02",
          "floor": "5th",
          "bedrooms": 3,
          "type": "3 Bedrooms",
          "category": "Typical Apartment",
          "finish": "Fully Finished",
          "area": 190,
          "view": "Garden",
          "price": 9478811,
          "floorplan": "3br-d"
        },
        {
          "code": "B02-506",
          "building": "B02",
          "floor": "5th",
          "bedrooms": 3,
          "type": "3 Bedrooms",
          "category": "Typical Apartment",
          "finish": "Fully Finished",
          "area": 183,
          "view": "Garden",
          "price": 9017760,
          "floorplan": "3br-d"
        },
        {
          "code": "B02-602",
          "building": "B02",
          "floor": "6th",
          "bedrooms": 3,
          "type": "3 Bedrooms",
          "category": "Typical Apartment",
          "finish": "Fully Finished",
          "area": 177,
          "view": "Garden",
          "price": 8888055,
          "floorplan": "3br-c"
        },
        {
          "code": "B02-605",
          "building": "B02",
          "floor": "6th",
          "bedrooms": 3,
          "type": "3 Bedrooms",
          "category": "Typical Apartment",
          "finish": "Fully Finished",
          "area": 153,
          "view": "Landscape",
          "price": 7380720,
          "floorplan": "3br-a"
        },
        {
          "code": "B02-705",
          "building": "B02",
          "floor": "7th",
          "bedrooms": 3,
          "type": "3 Bedrooms",
          "category": "Typical Apartment",
          "finish": "Fully Finished",
          "area": 140,
          "view": "Landscape",
          "price": 6082163,
          "floorplan": "3br-a"
        }
      ]
    },
    {
      "code": "B03",
      "pin": {
        "x": 0.595,
        "y": 0.131
      },
      "units": [
        {
          "code": "B03-201",
          "building": "B03",
          "floor": "2nd",
          "bedrooms": 2,
          "type": "2 Bedrooms",
          "category": "Typical Apartment",
          "finish": "Fully Finished",
          "area": 118,
          "view": "Street",
          "price": 6111810,
          "floorplan": "2br-a"
        },
        {
          "code": "B03-304",
          "building": "B03",
          "floor": "3rd",
          "bedrooms": 3,
          "type": "3 Bedrooms",
          "category": "Typical Apartment",
          "finish": "Fully Finished",
          "area": 140,
          "view": "Landscape",
          "price": 6082163,
          "floorplan": "3br-a"
        },
        {
          "code": "B03-306",
          "building": "B03",
          "floor": "3rd",
          "bedrooms": 2,
          "type": "2 Bedrooms",
          "category": "Typical Apartment",
          "finish": "Fully Finished",
          "area": 113,
          "view": "Garden",
          "price": 5852835,
          "floorplan": "2br-a"
        },
        {
          "code": "B03-406",
          "building": "B03",
          "floor": "4th",
          "bedrooms": 3,
          "type": "3 Bedrooms",
          "category": "Typical Apartment",
          "finish": "Fully Finished",
          "area": 153,
          "view": "Street",
          "price": 7380720,
          "floorplan": "3br-a"
        },
        {
          "code": "B03-506",
          "building": "B03",
          "floor": "5th",
          "bedrooms": 2,
          "type": "2 Bedrooms",
          "category": "Typical Apartment",
          "finish": "Fully Finished",
          "area": 129,
          "view": "Pool",
          "price": 6681555,
          "floorplan": "2br-b"
        },
        {
          "code": "B03-601",
          "building": "B03",
          "floor": "6th",
          "bedrooms": 3,
          "type": "3 Bedrooms",
          "category": "Typical Apartment",
          "finish": "Fully Finished",
          "area": 183,
          "view": "Landscape",
          "price": 9017760,
          "floorplan": "3br-d"
        },
        {
          "code": "B03-606",
          "building": "B03",
          "floor": "6th",
          "bedrooms": 3,
          "type": "3 Bedrooms",
          "category": "Typical Apartment",
          "finish": "Fully Finished",
          "area": 183,
          "view": "Street",
          "price": 9017760,
          "floorplan": "3br-d"
        },
        {
          "code": "B03-704",
          "building": "B03",
          "floor": "7th",
          "bedrooms": 3,
          "type": "3 Bedrooms",
          "category": "Typical Apartment",
          "finish": "Fully Finished",
          "area": 190,
          "view": "Garden",
          "price": 9478811,
          "floorplan": "3br-d"
        },
        {
          "code": "B03-706",
          "building": "B03",
          "floor": "7th",
          "bedrooms": 2,
          "type": "2 Bedrooms",
          "category": "Typical Apartment",
          "finish": "Fully Finished",
          "area": 118,
          "view": "Street",
          "price": 6111810,
          "floorplan": "2br-a"
        }
      ]
    },
    {
      "code": "B04",
      "pin": {
        "x": 0.756,
        "y": 0.12
      },
      "units": [
        {
          "code": "B04-204",
          "building": "B04",
          "floor": "2nd",
          "bedrooms": 2,
          "type": "2 Bedrooms",
          "category": "Typical Apartment",
          "finish": "Fully Finished",
          "area": 129,
          "view": "Landscape",
          "price": 6681555,
          "floorplan": "2br-b"
        },
        {
          "code": "B04-306",
          "building": "B04",
          "floor": "3rd",
          "bedrooms": 3,
          "type": "3 Bedrooms",
          "category": "Typical Apartment",
          "finish": "Fully Finished",
          "area": 173,
          "view": "Landscape",
          "price": 8687195,
          "floorplan": "3br-b"
        },
        {
          "code": "B04-403",
          "building": "B04",
          "floor": "4th",
          "bedrooms": 3,
          "type": "3 Bedrooms",
          "category": "Typical Apartment",
          "finish": "Fully Finished",
          "area": 183,
          "view": "Street",
          "price": 9017760,
          "floorplan": "3br-d"
        },
        {
          "code": "B04-502",
          "building": "B04",
          "floor": "5th",
          "bedrooms": 3,
          "type": "3 Bedrooms",
          "category": "Typical Apartment",
          "finish": "Fully Finished",
          "area": 183,
          "view": "Street",
          "price": 9017760,
          "floorplan": "3br-d"
        },
        {
          "code": "B04-503",
          "building": "B04",
          "floor": "5th",
          "bedrooms": 2,
          "type": "2 Bedrooms",
          "category": "Typical Apartment",
          "finish": "Fully Finished",
          "area": 129,
          "view": "Landscape",
          "price": 6681555,
          "floorplan": "2br-b"
        },
        {
          "code": "B04-605",
          "building": "B04",
          "floor": "6th",
          "bedrooms": 2,
          "type": "2 Bedrooms",
          "category": "Typical Apartment",
          "finish": "Fully Finished",
          "area": 125,
          "view": "Landscape",
          "price": 6375625,
          "floorplan": "2br-b"
        }
      ]
    },
    {
      "code": "B05",
      "pin": {
        "x": 0.752,
        "y": 0.304
      },
      "units": [
        {
          "code": "B05-103",
          "building": "B05",
          "floor": "1st",
          "bedrooms": 2,
          "type": "2 Bedrooms",
          "category": "Typical Apartment",
          "finish": "Fully Finished",
          "area": 124,
          "view": "Garden",
          "price": 6441058,
          "floorplan": "2br-b"
        },
        {
          "code": "B05-105",
          "building": "B05",
          "floor": "1st",
          "bedrooms": 2,
          "type": "2 Bedrooms",
          "category": "Typical Apartment",
          "finish": "Fully Finished",
          "area": 118,
          "view": "Pool",
          "price": 6111810,
          "floorplan": "2br-a"
        },
        {
          "code": "B05-206",
          "building": "B05",
          "floor": "2nd",
          "bedrooms": 3,
          "type": "3 Bedrooms",
          "category": "Typical Apartment",
          "finish": "Fully Finished",
          "area": 177,
          "view": "Landscape",
          "price": 8888055,
          "floorplan": "3br-c"
        },
        {
          "code": "B05-303",
          "building": "B05",
          "floor": "3rd",
          "bedrooms": 3,
          "type": "3 Bedrooms",
          "category": "Typical Apartment",
          "finish": "Fully Finished",
          "area": 140,
          "view": "Garden",
          "price": 6082163,
          "floorplan": "3br-a"
        },
        {
          "code": "B05-305",
          "building": "B05",
          "floor": "3rd",
          "bedrooms": 3,
          "type": "3 Bedrooms",
          "category": "Typical Apartment",
          "finish": "Fully Finished",
          "area": 173,
          "view": "Garden",
          "price": 8687195,
          "floorplan": "3br-b"
        },
        {
          "code": "B05-306",
          "building": "B05",
          "floor": "3rd",
          "bedrooms": 3,
          "type": "3 Bedrooms",
          "category": "Typical Apartment",
          "finish": "Fully Finished",
          "area": 177,
          "view": "Landscape",
          "price": 8888055,
          "floorplan": "3br-c"
        }
      ]
    },
    {
      "code": "B06",
      "pin": {
        "x": 0.773,
        "y": 0.502
      },
      "units": [
        {
          "code": "B06-203",
          "building": "B06",
          "floor": "2nd",
          "bedrooms": 3,
          "type": "3 Bedrooms",
          "category": "Typical Apartment",
          "finish": "Fully Finished",
          "area": 153,
          "view": "Pool",
          "price": 7380720,
          "floorplan": "3br-a"
        },
        {
          "code": "B06-301",
          "building": "B06",
          "floor": "3rd",
          "bedrooms": 2,
          "type": "2 Bedrooms",
          "category": "Typical Apartment",
          "finish": "Fully Finished",
          "area": 125,
          "view": "Landscape",
          "price": 6375625,
          "floorplan": "2br-b"
        },
        {
          "code": "B06-302",
          "building": "B06",
          "floor": "3rd",
          "bedrooms": 3,
          "type": "3 Bedrooms",
          "category": "Typical Apartment",
          "finish": "Fully Finished",
          "area": 140,
          "view": "Street",
          "price": 6082163,
          "floorplan": "3br-a"
        },
        {
          "code": "B06-402",
          "building": "B06",
          "floor": "4th",
          "bedrooms": 2,
          "type": "2 Bedrooms",
          "category": "Typical Apartment",
          "finish": "Fully Finished",
          "area": 113,
          "view": "Garden",
          "price": 5852835,
          "floorplan": "2br-a"
        },
        {
          "code": "B06-603",
          "building": "B06",
          "floor": "6th",
          "bedrooms": 3,
          "type": "3 Bedrooms",
          "category": "Typical Apartment",
          "finish": "Fully Finished",
          "area": 173,
          "view": "Street",
          "price": 8687195,
          "floorplan": "3br-b"
        },
        {
          "code": "B06-701",
          "building": "B06",
          "floor": "7th",
          "bedrooms": 2,
          "type": "2 Bedrooms",
          "category": "Typical Apartment",
          "finish": "Fully Finished",
          "area": 129,
          "view": "Pool",
          "price": 6681555,
          "floorplan": "2br-b"
        }
      ]
    },
    {
      "code": "B07",
      "pin": {
        "x": 0.756,
        "y": 0.618
      },
      "units": [
        {
          "code": "B07-102",
          "building": "B07",
          "floor": "1st",
          "bedrooms": 3,
          "type": "3 Bedrooms",
          "category": "Typical Apartment",
          "finish": "Fully Finished",
          "area": 173,
          "view": "Street",
          "price": 8687195,
          "floorplan": "3br-b"
        },
        {
          "code": "B07-106",
          "building": "B07",
          "floor": "1st",
          "bedrooms": 2,
          "type": "2 Bedrooms",
          "category": "Typical Apartment",
          "finish": "Fully Finished",
          "area": 118,
          "view": "Pool",
          "price": 6111810,
          "floorplan": "2br-a"
        },
        {
          "code": "B07-202",
          "building": "B07",
          "floor": "2nd",
          "bedrooms": 3,
          "type": "3 Bedrooms",
          "category": "Typical Apartment",
          "finish": "Fully Finished",
          "area": 140,
          "view": "Landscape",
          "price": 6082163,
          "floorplan": "3br-a"
        },
        {
          "code": "B07-204",
          "building": "B07",
          "floor": "2nd",
          "bedrooms": 2,
          "type": "2 Bedrooms",
          "category": "Typical Apartment",
          "finish": "Fully Finished",
          "area": 124,
          "view": "Street",
          "price": 6441058,
          "floorplan": "2br-b"
        },
        {
          "code": "B07-206",
          "building": "B07",
          "floor": "2nd",
          "bedrooms": 3,
          "type": "3 Bedrooms",
          "category": "Typical Apartment",
          "finish": "Fully Finished",
          "area": 177,
          "view": "Landscape",
          "price": 8888055,
          "floorplan": "3br-c"
        },
        {
          "code": "B07-304",
          "building": "B07",
          "floor": "3rd",
          "bedrooms": 3,
          "type": "3 Bedrooms",
          "category": "Typical Apartment",
          "finish": "Fully Finished",
          "area": 153,
          "view": "Pool",
          "price": 7380720,
          "floorplan": "3br-a"
        },
        {
          "code": "B07-402",
          "building": "B07",
          "floor": "4th",
          "bedrooms": 4,
          "type": "4 Bedrooms",
          "category": "Typical Apartment",
          "finish": "Fully Finished",
          "area": 179,
          "view": "Garden",
          "price": 8988485,
          "floorplan": "4br-a"
        },
        {
          "code": "B07-406",
          "building": "B07",
          "floor": "4th",
          "bedrooms": 2,
          "type": "2 Bedrooms",
          "category": "Typical Apartment",
          "finish": "Fully Finished",
          "area": 124,
          "view": "Garden",
          "price": 6441058,
          "floorplan": "2br-b"
        },
        {
          "code": "B07-705",
          "building": "B07",
          "floor": "7th",
          "bedrooms": 3,
          "type": "3 Bedrooms",
          "category": "Typical Apartment",
          "finish": "Fully Finished",
          "area": 153,
          "view": "Garden",
          "price": 7380720,
          "floorplan": "3br-a"
        }
      ]
    },
    {
      "code": "B08",
      "pin": {
        "x": 0.74,
        "y": 0.845
      },
      "units": [
        {
          "code": "B08-101",
          "building": "B08",
          "floor": "1st",
          "bedrooms": 2,
          "type": "2 Bedrooms",
          "category": "Typical Apartment",
          "finish": "Fully Finished",
          "area": 129,
          "view": "Garden",
          "price": 6681555,
          "floorplan": "2br-b"
        },
        {
          "code": "B08-104",
          "building": "B08",
          "floor": "1st",
          "bedrooms": 4,
          "type": "4 Bedrooms",
          "category": "Typical Apartment",
          "finish": "Fully Finished",
          "area": 179,
          "view": "Landscape",
          "price": 8988485,
          "floorplan": "4br-a"
        },
        {
          "code": "B08-204",
          "building": "B08",
          "floor": "2nd",
          "bedrooms": 4,
          "type": "4 Bedrooms",
          "category": "Typical Apartment",
          "finish": "Fully Finished",
          "area": 179,
          "view": "Street",
          "price": 8988485,
          "floorplan": "4br-a"
        },
        {
          "code": "B08-403",
          "building": "B08",
          "floor": "4th",
          "bedrooms": 3,
          "type": "3 Bedrooms",
          "category": "Typical Apartment",
          "finish": "Fully Finished",
          "area": 190,
          "view": "Street",
          "price": 9478811,
          "floorplan": "3br-d"
        },
        {
          "code": "B08-406",
          "building": "B08",
          "floor": "4th",
          "bedrooms": 3,
          "type": "3 Bedrooms",
          "category": "Typical Apartment",
          "finish": "Fully Finished",
          "area": 140,
          "view": "Street",
          "price": 6082163,
          "floorplan": "3br-a"
        },
        {
          "code": "B08-602",
          "building": "B08",
          "floor": "6th",
          "bedrooms": 2,
          "type": "2 Bedrooms",
          "category": "Typical Apartment",
          "finish": "Fully Finished",
          "area": 124,
          "view": "Landscape",
          "price": 6441058,
          "floorplan": "2br-b"
        },
        {
          "code": "B08-704",
          "building": "B08",
          "floor": "7th",
          "bedrooms": 2,
          "type": "2 Bedrooms",
          "category": "Typical Apartment",
          "finish": "Fully Finished",
          "area": 129,
          "view": "Street",
          "price": 6681555,
          "floorplan": "2br-b"
        }
      ]
    },
    {
      "code": "B09",
      "pin": {
        "x": 0.554,
        "y": 0.705
      },
      "units": [
        {
          "code": "B09-202",
          "building": "B09",
          "floor": "2nd",
          "bedrooms": 3,
          "type": "3 Bedrooms",
          "category": "Typical Apartment",
          "finish": "Fully Finished",
          "area": 177,
          "view": "Street",
          "price": 8888055,
          "floorplan": "3br-c"
        },
        {
          "code": "B09-301",
          "building": "B09",
          "floor": "3rd",
          "bedrooms": 2,
          "type": "2 Bedrooms",
          "category": "Typical Apartment",
          "finish": "Fully Finished",
          "area": 125,
          "view": "Garden",
          "price": 6375625,
          "floorplan": "2br-b"
        },
        {
          "code": "B09-304",
          "building": "B09",
          "floor": "3rd",
          "bedrooms": 3,
          "type": "3 Bedrooms",
          "category": "Typical Apartment",
          "finish": "Fully Finished",
          "area": 190,
          "view": "Pool",
          "price": 9478811,
          "floorplan": "3br-d"
        },
        {
          "code": "B09-305",
          "building": "B09",
          "floor": "3rd",
          "bedrooms": 2,
          "type": "2 Bedrooms",
          "category": "Typical Apartment",
          "finish": "Fully Finished",
          "area": 125,
          "view": "Landscape",
          "price": 6375625,
          "floorplan": "2br-b"
        },
        {
          "code": "B09-505",
          "building": "B09",
          "floor": "5th",
          "bedrooms": 2,
          "type": "2 Bedrooms",
          "category": "Typical Apartment",
          "finish": "Fully Finished",
          "area": 124,
          "view": "Garden",
          "price": 6441058,
          "floorplan": "2br-b"
        },
        {
          "code": "B09-506",
          "building": "B09",
          "floor": "5th",
          "bedrooms": 2,
          "type": "2 Bedrooms",
          "category": "Typical Apartment",
          "finish": "Fully Finished",
          "area": 125,
          "view": "Garden",
          "price": 6375625,
          "floorplan": "2br-b"
        },
        {
          "code": "B09-605",
          "building": "B09",
          "floor": "6th",
          "bedrooms": 3,
          "type": "3 Bedrooms",
          "category": "Typical Apartment",
          "finish": "Fully Finished",
          "area": 177,
          "view": "Landscape",
          "price": 8888055,
          "floorplan": "3br-c"
        },
        {
          "code": "B09-702",
          "building": "B09",
          "floor": "7th",
          "bedrooms": 4,
          "type": "4 Bedrooms",
          "category": "Typical Apartment",
          "finish": "Fully Finished",
          "area": 179,
          "view": "Pool",
          "price": 8988485,
          "floorplan": "4br-a"
        },
        {
          "code": "B09-705",
          "building": "B09",
          "floor": "7th",
          "bedrooms": 3,
          "type": "3 Bedrooms",
          "category": "Typical Apartment",
          "finish": "Fully Finished",
          "area": 190,
          "view": "Garden",
          "price": 9478811,
          "floorplan": "3br-d"
        }
      ]
    },
    {
      "code": "B10",
      "pin": {
        "x": 0.421,
        "y": 0.616
      },
      "units": [
        {
          "code": "B10-102",
          "building": "B10",
          "floor": "1st",
          "bedrooms": 3,
          "type": "3 Bedrooms",
          "category": "Typical Apartment",
          "finish": "Fully Finished",
          "area": 190,
          "view": "Garden",
          "price": 9478811,
          "floorplan": "3br-d"
        },
        {
          "code": "B10-103",
          "building": "B10",
          "floor": "1st",
          "bedrooms": 4,
          "type": "4 Bedrooms",
          "category": "Typical Apartment",
          "finish": "Fully Finished",
          "area": 179,
          "view": "Street",
          "price": 8988485,
          "floorplan": "4br-a"
        },
        {
          "code": "B10-201",
          "building": "B10",
          "floor": "2nd",
          "bedrooms": 3,
          "type": "3 Bedrooms",
          "category": "Typical Apartment",
          "finish": "Fully Finished",
          "area": 183,
          "view": "Pool",
          "price": 9017760,
          "floorplan": "3br-d"
        },
        {
          "code": "B10-306",
          "building": "B10",
          "floor": "3rd",
          "bedrooms": 3,
          "type": "3 Bedrooms",
          "category": "Typical Apartment",
          "finish": "Fully Finished",
          "area": 140,
          "view": "Garden",
          "price": 6082163,
          "floorplan": "3br-a"
        },
        {
          "code": "B10-501",
          "building": "B10",
          "floor": "5th",
          "bedrooms": 3,
          "type": "3 Bedrooms",
          "category": "Typical Apartment",
          "finish": "Fully Finished",
          "area": 140,
          "view": "Garden",
          "price": 6082163,
          "floorplan": "3br-a"
        },
        {
          "code": "B10-503",
          "building": "B10",
          "floor": "5th",
          "bedrooms": 3,
          "type": "3 Bedrooms",
          "category": "Typical Apartment",
          "finish": "Fully Finished",
          "area": 140,
          "view": "Street",
          "price": 6082163,
          "floorplan": "3br-a"
        },
        {
          "code": "B10-504",
          "building": "B10",
          "floor": "5th",
          "bedrooms": 3,
          "type": "3 Bedrooms",
          "category": "Typical Apartment",
          "finish": "Fully Finished",
          "area": 173,
          "view": "Landscape",
          "price": 8687195,
          "floorplan": "3br-b"
        }
      ]
    },
    {
      "code": "B11",
      "pin": {
        "x": 0.248,
        "y": 0.525
      },
      "units": [
        {
          "code": "B11-204",
          "building": "B11",
          "floor": "2nd",
          "bedrooms": 3,
          "type": "3 Bedrooms",
          "category": "Typical Apartment",
          "finish": "Fully Finished",
          "area": 153,
          "view": "Garden",
          "price": 7380720,
          "floorplan": "3br-a"
        },
        {
          "code": "B11-401",
          "building": "B11",
          "floor": "4th",
          "bedrooms": 2,
          "type": "2 Bedrooms",
          "category": "Typical Apartment",
          "finish": "Fully Finished",
          "area": 129,
          "view": "Garden",
          "price": 6681555,
          "floorplan": "2br-b"
        },
        {
          "code": "B11-403",
          "building": "B11",
          "floor": "4th",
          "bedrooms": 3,
          "type": "3 Bedrooms",
          "category": "Typical Apartment",
          "finish": "Fully Finished",
          "area": 190,
          "view": "Pool",
          "price": 9478811,
          "floorplan": "3br-d"
        },
        {
          "code": "B11-405",
          "building": "B11",
          "floor": "4th",
          "bedrooms": 3,
          "type": "3 Bedrooms",
          "category": "Typical Apartment",
          "finish": "Fully Finished",
          "area": 153,
          "view": "Garden",
          "price": 7380720,
          "floorplan": "3br-a"
        },
        {
          "code": "B11-501",
          "building": "B11",
          "floor": "5th",
          "bedrooms": 2,
          "type": "2 Bedrooms",
          "category": "Typical Apartment",
          "finish": "Fully Finished",
          "area": 125,
          "view": "Garden",
          "price": 6375625,
          "floorplan": "2br-b"
        },
        {
          "code": "B11-604",
          "building": "B11",
          "floor": "6th",
          "bedrooms": 3,
          "type": "3 Bedrooms",
          "category": "Typical Apartment",
          "finish": "Fully Finished",
          "area": 190,
          "view": "Street",
          "price": 9478811,
          "floorplan": "3br-d"
        },
        {
          "code": "B11-702",
          "building": "B11",
          "floor": "7th",
          "bedrooms": 2,
          "type": "2 Bedrooms",
          "category": "Typical Apartment",
          "finish": "Fully Finished",
          "area": 129,
          "view": "Garden",
          "price": 6681555,
          "floorplan": "2br-b"
        },
        {
          "code": "B11-704",
          "building": "B11",
          "floor": "7th",
          "bedrooms": 2,
          "type": "2 Bedrooms",
          "category": "Typical Apartment",
          "finish": "Fully Finished",
          "area": 129,
          "view": "Pool",
          "price": 6681555,
          "floorplan": "2br-b"
        }
      ]
    },
    {
      "code": "B12",
      "pin": {
        "x": 0.236,
        "y": 0.31
      },
      "units": [
        {
          "code": "B12-202",
          "building": "B12",
          "floor": "2nd",
          "bedrooms": 2,
          "type": "2 Bedrooms",
          "category": "Typical Apartment",
          "finish": "Fully Finished",
          "area": 125,
          "view": "Garden",
          "price": 6375625,
          "floorplan": "2br-b"
        },
        {
          "code": "B12-203",
          "building": "B12",
          "floor": "2nd",
          "bedrooms": 2,
          "type": "2 Bedrooms",
          "category": "Typical Apartment",
          "finish": "Fully Finished",
          "area": 129,
          "view": "Pool",
          "price": 6681555,
          "floorplan": "2br-b"
        },
        {
          "code": "B12-301",
          "building": "B12",
          "floor": "3rd",
          "bedrooms": 3,
          "type": "3 Bedrooms",
          "category": "Typical Apartment",
          "finish": "Fully Finished",
          "area": 177,
          "view": "Garden",
          "price": 8888055,
          "floorplan": "3br-c"
        },
        {
          "code": "B12-302",
          "building": "B12",
          "floor": "3rd",
          "bedrooms": 2,
          "type": "2 Bedrooms",
          "category": "Typical Apartment",
          "finish": "Fully Finished",
          "area": 118,
          "view": "Pool",
          "price": 6111810,
          "floorplan": "2br-a"
        },
        {
          "code": "B12-403",
          "building": "B12",
          "floor": "4th",
          "bedrooms": 3,
          "type": "3 Bedrooms",
          "category": "Typical Apartment",
          "finish": "Fully Finished",
          "area": 173,
          "view": "Pool",
          "price": 8687195,
          "floorplan": "3br-b"
        },
        {
          "code": "B12-602",
          "building": "B12",
          "floor": "6th",
          "bedrooms": 3,
          "type": "3 Bedrooms",
          "category": "Typical Apartment",
          "finish": "Fully Finished",
          "area": 153,
          "view": "Landscape",
          "price": 7380720,
          "floorplan": "3br-a"
        }
      ]
    }
  ],
  "assets": {
    "masterplan": "assets/masterplan.png",
    "renders": [
      "assets/pdf/render1.jpg",
      "assets/pdf/render2.jpg",
      "assets/pdf/render3.jpg"
    ]
  },
  "isSeed": true
};
  if (typeof module !== "undefined" && module.exports) module.exports = DATA;
  else root.OfferData = DATA;
})(typeof window !== "undefined" ? window : this);
