/*
 * Source of truth for the Ion demo inventory.
 * Emits BOTH:
 *   - js/data.js                              (the app's data module)
 *   - assets/deliverables/Ion-Phase2-Units-DEMO.xlsx  (Excel template/deliverable)
 * so the two can never drift. Run:  node scripts/generate-data.js
 *
 * Prices & areas are REAL (from the published Ion Phase-2 price list).
 * Unit codes / floors / views are realistic demo assignments.
 */
const fs = require("fs");
const path = require("path");
const XLSX = require("xlsx");
const ROOT = path.join(__dirname, "..");

// Building pin positions (fraction of assets/masterplan.png, 1210x1210).
const PINS = {
  B01: { x: 0.227, y: 0.135 }, B02: { x: 0.388, y: 0.139 }, B03: { x: 0.595, y: 0.131 },
  B04: { x: 0.756, y: 0.120 }, B05: { x: 0.752, y: 0.304 }, B06: { x: 0.773, y: 0.502 },
  B07: { x: 0.756, y: 0.618 }, B08: { x: 0.740, y: 0.845 }, B09: { x: 0.554, y: 0.705 },
  B10: { x: 0.421, y: 0.616 }, B11: { x: 0.248, y: 0.525 }, B12: { x: 0.236, y: 0.310 },
};

// Sellable types — REAL area/price from the price list, mapped to a floor-plan asset.
const CATALOG = [
  { area: 113, bedrooms: 2, price: 5852835, floorplan: "2br-a" },
  { area: 118, bedrooms: 2, price: 6111810, floorplan: "2br-a" },
  { area: 124, bedrooms: 2, price: 6441058, floorplan: "2br-b" },
  { area: 125, bedrooms: 2, price: 6375625, floorplan: "2br-b" },
  { area: 129, bedrooms: 2, price: 6681555, floorplan: "2br-b" },
  { area: 140, bedrooms: 3, price: 6082163, floorplan: "3br-a" },
  { area: 153, bedrooms: 3, price: 7380720, floorplan: "3br-a" },
  { area: 173, bedrooms: 3, price: 8687195, floorplan: "3br-b" },
  { area: 177, bedrooms: 3, price: 8888055, floorplan: "3br-c" },
  { area: 183, bedrooms: 3, price: 9017760, floorplan: "3br-d" },
  { area: 190, bedrooms: 3, price: 9478811, floorplan: "3br-d" },
  { area: 179, bedrooms: 4, price: 8988485, floorplan: "4br-a" },
];
const VIEWS = ["Garden", "Pool", "Landscape", "Street"];
const FLOORS = ["Ground", "1st", "2nd", "3rd", "4th", "5th", "6th", "7th"];

// Deterministic PRNG so the demo is stable between runs.
function mulberry32(a) {
  return function () {
    a |= 0; a = (a + 0x6D2B79F5) | 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}
const rnd = mulberry32(20260716);
const pick = (arr) => arr[Math.floor(rnd() * arr.length)];

const buildingCodes = Object.keys(PINS);
const rows = []; // flat rows for Excel
const buildings = buildingCodes.map(function (code) {
  const nUnits = 6 + Math.floor(rnd() * 4); // 6–9 units
  const units = [];
  const used = {};
  for (let i = 0; i < nUnits; i++) {
    const cat = pick(CATALOG);
    const floorIdx = 1 + Math.floor(rnd() * 7); // 1st..7th (skip Ground for apartments)
    const floorNum = floorIdx;
    let unitNo, unitCode;
    do {
      unitNo = 1 + Math.floor(rnd() * 6);
      unitCode = code + "-" + floorNum + String(unitNo).padStart(2, "0");
    } while (used[unitCode]);
    used[unitCode] = true;

    const unit = {
      code: unitCode,
      building: code,
      floor: FLOORS[floorIdx],
      bedrooms: cat.bedrooms,
      type: cat.bedrooms + " Bedrooms",
      category: "Typical Apartment",
      finish: "Fully Finished",
      area: cat.area,
      view: pick(VIEWS),
      price: cat.price,
      floorplan: cat.floorplan,
    };
    units.push(unit);
    rows.push({
      Building: code, "Unit Code": unitCode, Floor: unit.floor,
      Type: unit.type, "BUA (m²)": unit.area, View: unit.view,
      "Installment Price (LE)": unit.price, Finish: unit.finish,
      Status: "Available", "Floor Plan": unit.floorplan,
    });
  }
  units.sort(function (a, b) { return a.code.localeCompare(b.code); });
  return { code: code, pin: PINS[code], units: units };
});

// ── Write Excel deliverable ──
const ws = XLSX.utils.json_to_sheet(rows);
ws["!cols"] = [{ wch: 9 }, { wch: 11 }, { wch: 8 }, { wch: 12 }, { wch: 9 }, { wch: 11 }, { wch: 20 }, { wch: 14 }, { wch: 11 }, { wch: 10 }];
const wb = XLSX.utils.book_new();
XLSX.utils.book_append_sheet(wb, ws, "Ion Phase 2 Units");
const xlsxDir = path.join(ROOT, "assets/deliverables");
fs.mkdirSync(xlsxDir, { recursive: true });
XLSX.writeFile(wb, path.join(xlsxDir, "Ion-Phase2-Units-DEMO.xlsx"));

// ── Write app data module ──
const dataModule = `/*
 * AUTO-GENERATED by scripts/generate-data.js — do not edit by hand.
 * Ion — Phase 2 demo inventory (real prices/areas, demo unit codes/floors/views).
 */
(function (root) {
  "use strict";
  var DATA = ${JSON.stringify({
    project: { name: "Ion", phase: "Phase 2", developer: "Prime Developments", tagline: "Innovative living", deliveryText: "4 Years" },
    buildings: buildings,
    assets: {
      masterplan: "assets/masterplan.png",
      renders: ["assets/pdf/render1.jpg", "assets/pdf/render2.jpg", "assets/pdf/render3.jpg"],
    },
    isSeed: true,
  }, null, 2)};
  if (typeof module !== "undefined" && module.exports) module.exports = DATA;
  else root.OfferData = DATA;
})(typeof window !== "undefined" ? window : this);
`;
fs.writeFileSync(path.join(ROOT, "js/data.js"), dataModule);

console.log("Generated " + rows.length + " units across " + buildings.length + " buildings.");
console.log(" -> assets/deliverables/Ion-Phase2-Units-DEMO.xlsx");
console.log(" -> js/data.js");
